triggers:
  - name: triggertestpp
    type: trigger
    source:
      message: 'fdduffffdgrl1vvh23'
      
  #- name: triggertest2
  #  type: trigger
  #  source:
   #   message: 'new teswt2'
    #  counter: 1
      
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'tewwt3'
    #  counter: 3
