jobs:
  - name: ecstestmuljobs1
    type: manifest
    steps:
      - GET: sample-newtest001
      - GET: new-imagemultijobs
      - GET: triggetestpp

  - name: ecstestmuljobs2
    type: manifest
    steps:
      - GET: sample-newtest001
      - GET: new-imagemultijobs
      - GET: triggetestpp
